baseurl = "/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Erik-Jan van Kesteren"
title = "Erik-Jan van Kesteren"
disqusshortname = ""
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "A blog about statistics with R (and other stuff I find interesting)"
copyright = "Copyright Â© 2018 Erik-Jan van Kesteren"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/favicon.png"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjslanguages = ["r", "python", "yaml", "js"]
progressively = true
share = false
latestpostcount = 10
github = "vankesteren"
email = "e.vankesteren1@uu.nl"
linkedin = "erikjanvankesteren"
twitter = "ejvankesteren"
#facebook = "facebook_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
#githubRepo = "vankesteren/blog-source"
small_banner_logo = false
uselatex = true
